project_id = "sminapuzozzsnfsdfgbc"

[functions.discovery-chat]
verify_jwt = false

[functions.begin-here-chat]
verify_jwt = false

[functions.aura-reading]
verify_jwt = false

[functions.iris-reading]
verify_jwt = false

[functions.fingerprint-reading]
verify_jwt = false

[functions.soul-profile-generate]
verify_jwt = false

[functions.send-soul-profile-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.gene-key-reading]
verify_jwt = false

[functions.horoscope-generate]
verify_jwt = false

[functions.generate-transmission-text]
verify_jwt = false

[functions.generate-transmission-audio]
verify_jwt = true

[functions.save-transmission]
verify_jwt = true

[functions.sign-transmission]
verify_jwt = true
