/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WisdomRouteImport } from './routes/wisdom'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as TrueTimelineRouteImport } from './routes/true-timeline'
import { Route as TransmissionsRouteImport } from './routes/transmissions'
import { Route as TheSacredJourneyRouteImport } from './routes/the-sacred-journey'
import { Route as TeachingsRouteImport } from './routes/teachings'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SovereignRouteImport } from './routes/sovereign'
import { Route as SoulQuizRouteImport } from './routes/soul-quiz'
import { Route as SoulProfileRouteImport } from './routes/soul-profile'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RealityMapRouteImport } from './routes/reality-map'
import { Route as ReadingsRouteImport } from './routes/readings'
import { Route as PractitionersRouteImport } from './routes/practitioners'
import { Route as PillarsRouteImport } from './routes/pillars'
import { Route as NumerologyRouteImport } from './routes/numerology'
import { Route as NatureBookingRouteImport } from './routes/nature-booking'
import { Route as MyReadingsRouteImport } from './routes/my-readings'
import { Route as MeetWilliamRouteImport } from './routes/meet-william'
import { Route as MeditationsRouteImport } from './routes/meditations'
import { Route as KimAlfanoRouteImport } from './routes/kim-alfano'
import { Route as HoroscopeRouteImport } from './routes/horoscope'
import { Route as HigherVibesRouteImport } from './routes/higher-vibes'
import { Route as HiddenTruthRouteImport } from './routes/hidden-truth'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GeneKeysRouteImport } from './routes/gene-keys'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactWilliamRouteImport } from './routes/contact-william'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsciousnessMapRouteImport } from './routes/consciousness-map'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as BookSessionRouteImport } from './routes/book-session'
import { Route as BloodTypeRouteImport } from './routes/blood-type'
import { Route as BirthChartRouteImport } from './routes/birth-chart'
import { Route as BeginHereRouteImport } from './routes/begin-here'
import { Route as AwakeningAssessmentRouteImport } from './routes/awakening-assessment'
import { Route as AuraReaderRouteImport } from './routes/aura-reader'
import { Route as AstrologyRouteImport } from './routes/astrology'
import { Route as AdminCodesRouteImport } from './routes/admin-codes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SovereignIndexRouteImport } from './routes/sovereign.index'
import { Route as WisdomTheTrueStoryOfJeshuaRouteImport } from './routes/wisdom_.the-true-story-of-jeshua'
import { Route as WisdomSuppressedSacredTextsRouteImport } from './routes/wisdom_.suppressed-sacred-texts'
import { Route as WisdomSacredPlantsRouteImport } from './routes/wisdom_.sacred-plants'
import { Route as WisdomPlantMedicinesRouteImport } from './routes/wisdom_.plant-medicines'
import { Route as WisdomOriginsRouteImport } from './routes/wisdom_.origins'
import { Route as WisdomMatrixOriginsRouteImport } from './routes/wisdom_.matrix-origins'
import { Route as SovereignWelcomeRouteImport } from './routes/sovereign.welcome'
import { Route as SovereignVipWaitlistRouteImport } from './routes/sovereign.vip-waitlist'
import { Route as SovereignTermsRouteImport } from './routes/sovereign.terms'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as SovereignPortalIndexRouteImport } from './routes/sovereign.portal.index'
import { Route as SovereignPortalOnboardingRouteImport } from './routes/sovereign.portal.onboarding'
import { Route as SovereignPortalMorningRitualRouteImport } from './routes/sovereign.portal.morning-ritual'
import { Route as SovereignPortalDashboardRouteImport } from './routes/sovereign.portal.dashboard'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WisdomRoute = WisdomRouteImport.update({
  id: '/wisdom',
  path: '/wisdom',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const TrueTimelineRoute = TrueTimelineRouteImport.update({
  id: '/true-timeline',
  path: '/true-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TransmissionsRoute = TransmissionsRouteImport.update({
  id: '/transmissions',
  path: '/transmissions',
  getParentRoute: () => rootRouteImport,
} as any)
const TheSacredJourneyRoute = TheSacredJourneyRouteImport.update({
  id: '/the-sacred-journey',
  path: '/the-sacred-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingsRoute = TeachingsRouteImport.update({
  id: '/teachings',
  path: '/teachings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SovereignRoute = SovereignRouteImport.update({
  id: '/sovereign',
  path: '/sovereign',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulQuizRoute = SoulQuizRouteImport.update({
  id: '/soul-quiz',
  path: '/soul-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulProfileRoute = SoulProfileRouteImport.update({
  id: '/soul-profile',
  path: '/soul-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RealityMapRoute = RealityMapRouteImport.update({
  id: '/reality-map',
  path: '/reality-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingsRoute = ReadingsRouteImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionersRoute = PractitionersRouteImport.update({
  id: '/practitioners',
  path: '/practitioners',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarsRoute = PillarsRouteImport.update({
  id: '/pillars',
  path: '/pillars',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerologyRoute = NumerologyRouteImport.update({
  id: '/numerology',
  path: '/numerology',
  getParentRoute: () => rootRouteImport,
} as any)
const NatureBookingRoute = NatureBookingRouteImport.update({
  id: '/nature-booking',
  path: '/nature-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReadingsRoute = MyReadingsRouteImport.update({
  id: '/my-readings',
  path: '/my-readings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetWilliamRoute = MeetWilliamRouteImport.update({
  id: '/meet-william',
  path: '/meet-william',
  getParentRoute: () => rootRouteImport,
} as any)
const MeditationsRoute = MeditationsRouteImport.update({
  id: '/meditations',
  path: '/meditations',
  getParentRoute: () => rootRouteImport,
} as any)
const KimAlfanoRoute = KimAlfanoRouteImport.update({
  id: '/kim-alfano',
  path: '/kim-alfano',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopeRoute = HoroscopeRouteImport.update({
  id: '/horoscope',
  path: '/horoscope',
  getParentRoute: () => rootRouteImport,
} as any)
const HigherVibesRoute = HigherVibesRouteImport.update({
  id: '/higher-vibes',
  path: '/higher-vibes',
  getParentRoute: () => rootRouteImport,
} as any)
const HiddenTruthRoute = HiddenTruthRouteImport.update({
  id: '/hidden-truth',
  path: '/hidden-truth',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneKeysRoute = GeneKeysRouteImport.update({
  id: '/gene-keys',
  path: '/gene-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactWilliamRoute = ContactWilliamRouteImport.update({
  id: '/contact-william',
  path: '/contact-william',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsciousnessMapRoute = ConsciousnessMapRouteImport.update({
  id: '/consciousness-map',
  path: '/consciousness-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSessionRoute = BookSessionRouteImport.update({
  id: '/book-session',
  path: '/book-session',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodTypeRoute = BloodTypeRouteImport.update({
  id: '/blood-type',
  path: '/blood-type',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthChartRoute = BirthChartRouteImport.update({
  id: '/birth-chart',
  path: '/birth-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginHereRoute = BeginHereRouteImport.update({
  id: '/begin-here',
  path: '/begin-here',
  getParentRoute: () => rootRouteImport,
} as any)
const AwakeningAssessmentRoute = AwakeningAssessmentRouteImport.update({
  id: '/awakening-assessment',
  path: '/awakening-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraReaderRoute = AuraReaderRouteImport.update({
  id: '/aura-reader',
  path: '/aura-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyRoute = AstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/admin-codes',
  path: '/admin-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SovereignIndexRoute = SovereignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SovereignRoute,
} as any)
const WisdomTheTrueStoryOfJeshuaRoute =
  WisdomTheTrueStoryOfJeshuaRouteImport.update({
    id: '/wisdom_/the-true-story-of-jeshua',
    path: '/wisdom/the-true-story-of-jeshua',
    getParentRoute: () => rootRouteImport,
  } as any)
const WisdomSuppressedSacredTextsRoute =
  WisdomSuppressedSacredTextsRouteImport.update({
    id: '/wisdom_/suppressed-sacred-texts',
    path: '/wisdom/suppressed-sacred-texts',
    getParentRoute: () => rootRouteImport,
  } as any)
const WisdomSacredPlantsRoute = WisdomSacredPlantsRouteImport.update({
  id: '/wisdom_/sacred-plants',
  path: '/wisdom/sacred-plants',
  getParentRoute: () => rootRouteImport,
} as any)
const WisdomPlantMedicinesRoute = WisdomPlantMedicinesRouteImport.update({
  id: '/wisdom_/plant-medicines',
  path: '/wisdom/plant-medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const WisdomOriginsRoute = WisdomOriginsRouteImport.update({
  id: '/wisdom_/origins',
  path: '/wisdom/origins',
  getParentRoute: () => rootRouteImport,
} as any)
const WisdomMatrixOriginsRoute = WisdomMatrixOriginsRouteImport.update({
  id: '/wisdom_/matrix-origins',
  path: '/wisdom/matrix-origins',
  getParentRoute: () => rootRouteImport,
} as any)
const SovereignWelcomeRoute = SovereignWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => SovereignRoute,
} as any)
const SovereignVipWaitlistRoute = SovereignVipWaitlistRouteImport.update({
  id: '/vip-waitlist',
  path: '/vip-waitlist',
  getParentRoute: () => SovereignRoute,
} as any)
const SovereignTermsRoute = SovereignTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SovereignRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const SovereignPortalIndexRoute = SovereignPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => SovereignRoute,
} as any)
const SovereignPortalOnboardingRoute =
  SovereignPortalOnboardingRouteImport.update({
    id: '/portal/onboarding',
    path: '/portal/onboarding',
    getParentRoute: () => SovereignRoute,
  } as any)
const SovereignPortalMorningRitualRoute =
  SovereignPortalMorningRitualRouteImport.update({
    id: '/portal/morning-ritual',
    path: '/portal/morning-ritual',
    getParentRoute: () => SovereignRoute,
  } as any)
const SovereignPortalDashboardRoute =
  SovereignPortalDashboardRouteImport.update({
    id: '/portal/dashboard',
    path: '/portal/dashboard',
    getParentRoute: () => SovereignRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-codes': typeof AdminCodesRoute
  '/astrology': typeof AstrologyRoute
  '/aura-reader': typeof AuraReaderRoute
  '/awakening-assessment': typeof AwakeningAssessmentRoute
  '/begin-here': typeof BeginHereRoute
  '/birth-chart': typeof BirthChartRoute
  '/blood-type': typeof BloodTypeRoute
  '/book-session': typeof BookSessionRoute
  '/challenge': typeof ChallengeRoute
  '/consciousness-map': typeof ConsciousnessMapRoute
  '/contact': typeof ContactRoute
  '/contact-william': typeof ContactWilliamRoute
  '/dashboard': typeof DashboardRoute
  '/discovery': typeof DiscoveryRoute
  '/events': typeof EventsRoute
  '/gene-keys': typeof GeneKeysRoute
  '/guide': typeof GuideRoute
  '/health': typeof HealthRoute
  '/hidden-truth': typeof HiddenTruthRoute
  '/higher-vibes': typeof HigherVibesRoute
  '/horoscope': typeof HoroscopeRoute
  '/kim-alfano': typeof KimAlfanoRoute
  '/meditations': typeof MeditationsRoute
  '/meet-william': typeof MeetWilliamRoute
  '/my-readings': typeof MyReadingsRoute
  '/nature-booking': typeof NatureBookingRoute
  '/numerology': typeof NumerologyRoute
  '/pillars': typeof PillarsRoute
  '/practitioners': typeof PractitionersRoute
  '/readings': typeof ReadingsRoute
  '/reality-map': typeof RealityMapRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/soul-profile': typeof SoulProfileRoute
  '/soul-quiz': typeof SoulQuizRoute
  '/sovereign': typeof SovereignRouteWithChildren
  '/store': typeof StoreRoute
  '/teachings': typeof TeachingsRoute
  '/the-sacred-journey': typeof TheSacredJourneyRoute
  '/transmissions': typeof TransmissionsRoute
  '/true-timeline': typeof TrueTimelineRoute
  '/visit': typeof VisitRoute
  '/welcome': typeof WelcomeRoute
  '/wisdom': typeof WisdomRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/product/$handle': typeof ProductHandleRoute
  '/profile/$id': typeof ProfileIdRoute
  '/sovereign/terms': typeof SovereignTermsRoute
  '/sovereign/vip-waitlist': typeof SovereignVipWaitlistRoute
  '/sovereign/welcome': typeof SovereignWelcomeRoute
  '/wisdom/matrix-origins': typeof WisdomMatrixOriginsRoute
  '/wisdom/origins': typeof WisdomOriginsRoute
  '/wisdom/plant-medicines': typeof WisdomPlantMedicinesRoute
  '/wisdom/sacred-plants': typeof WisdomSacredPlantsRoute
  '/wisdom/suppressed-sacred-texts': typeof WisdomSuppressedSacredTextsRoute
  '/wisdom/the-true-story-of-jeshua': typeof WisdomTheTrueStoryOfJeshuaRoute
  '/sovereign/': typeof SovereignIndexRoute
  '/sovereign/portal/dashboard': typeof SovereignPortalDashboardRoute
  '/sovereign/portal/morning-ritual': typeof SovereignPortalMorningRitualRoute
  '/sovereign/portal/onboarding': typeof SovereignPortalOnboardingRoute
  '/sovereign/portal/': typeof SovereignPortalIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-codes': typeof AdminCodesRoute
  '/astrology': typeof AstrologyRoute
  '/aura-reader': typeof AuraReaderRoute
  '/awakening-assessment': typeof AwakeningAssessmentRoute
  '/begin-here': typeof BeginHereRoute
  '/birth-chart': typeof BirthChartRoute
  '/blood-type': typeof BloodTypeRoute
  '/book-session': typeof BookSessionRoute
  '/challenge': typeof ChallengeRoute
  '/consciousness-map': typeof ConsciousnessMapRoute
  '/contact': typeof ContactRoute
  '/contact-william': typeof ContactWilliamRoute
  '/dashboard': typeof DashboardRoute
  '/discovery': typeof DiscoveryRoute
  '/events': typeof EventsRoute
  '/gene-keys': typeof GeneKeysRoute
  '/guide': typeof GuideRoute
  '/health': typeof HealthRoute
  '/hidden-truth': typeof HiddenTruthRoute
  '/higher-vibes': typeof HigherVibesRoute
  '/horoscope': typeof HoroscopeRoute
  '/kim-alfano': typeof KimAlfanoRoute
  '/meditations': typeof MeditationsRoute
  '/meet-william': typeof MeetWilliamRoute
  '/my-readings': typeof MyReadingsRoute
  '/nature-booking': typeof NatureBookingRoute
  '/numerology': typeof NumerologyRoute
  '/pillars': typeof PillarsRoute
  '/practitioners': typeof PractitionersRoute
  '/readings': typeof ReadingsRoute
  '/reality-map': typeof RealityMapRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/soul-profile': typeof SoulProfileRoute
  '/soul-quiz': typeof SoulQuizRoute
  '/store': typeof StoreRoute
  '/teachings': typeof TeachingsRoute
  '/the-sacred-journey': typeof TheSacredJourneyRoute
  '/transmissions': typeof TransmissionsRoute
  '/true-timeline': typeof TrueTimelineRoute
  '/visit': typeof VisitRoute
  '/welcome': typeof WelcomeRoute
  '/wisdom': typeof WisdomRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/product/$handle': typeof ProductHandleRoute
  '/profile/$id': typeof ProfileIdRoute
  '/sovereign/terms': typeof SovereignTermsRoute
  '/sovereign/vip-waitlist': typeof SovereignVipWaitlistRoute
  '/sovereign/welcome': typeof SovereignWelcomeRoute
  '/wisdom/matrix-origins': typeof WisdomMatrixOriginsRoute
  '/wisdom/origins': typeof WisdomOriginsRoute
  '/wisdom/plant-medicines': typeof WisdomPlantMedicinesRoute
  '/wisdom/sacred-plants': typeof WisdomSacredPlantsRoute
  '/wisdom/suppressed-sacred-texts': typeof WisdomSuppressedSacredTextsRoute
  '/wisdom/the-true-story-of-jeshua': typeof WisdomTheTrueStoryOfJeshuaRoute
  '/sovereign': typeof SovereignIndexRoute
  '/sovereign/portal/dashboard': typeof SovereignPortalDashboardRoute
  '/sovereign/portal/morning-ritual': typeof SovereignPortalMorningRitualRoute
  '/sovereign/portal/onboarding': typeof SovereignPortalOnboardingRoute
  '/sovereign/portal': typeof SovereignPortalIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-codes': typeof AdminCodesRoute
  '/astrology': typeof AstrologyRoute
  '/aura-reader': typeof AuraReaderRoute
  '/awakening-assessment': typeof AwakeningAssessmentRoute
  '/begin-here': typeof BeginHereRoute
  '/birth-chart': typeof BirthChartRoute
  '/blood-type': typeof BloodTypeRoute
  '/book-session': typeof BookSessionRoute
  '/challenge': typeof ChallengeRoute
  '/consciousness-map': typeof ConsciousnessMapRoute
  '/contact': typeof ContactRoute
  '/contact-william': typeof ContactWilliamRoute
  '/dashboard': typeof DashboardRoute
  '/discovery': typeof DiscoveryRoute
  '/events': typeof EventsRoute
  '/gene-keys': typeof GeneKeysRoute
  '/guide': typeof GuideRoute
  '/health': typeof HealthRoute
  '/hidden-truth': typeof HiddenTruthRoute
  '/higher-vibes': typeof HigherVibesRoute
  '/horoscope': typeof HoroscopeRoute
  '/kim-alfano': typeof KimAlfanoRoute
  '/meditations': typeof MeditationsRoute
  '/meet-william': typeof MeetWilliamRoute
  '/my-readings': typeof MyReadingsRoute
  '/nature-booking': typeof NatureBookingRoute
  '/numerology': typeof NumerologyRoute
  '/pillars': typeof PillarsRoute
  '/practitioners': typeof PractitionersRoute
  '/readings': typeof ReadingsRoute
  '/reality-map': typeof RealityMapRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/soul-profile': typeof SoulProfileRoute
  '/soul-quiz': typeof SoulQuizRoute
  '/sovereign': typeof SovereignRouteWithChildren
  '/store': typeof StoreRoute
  '/teachings': typeof TeachingsRoute
  '/the-sacred-journey': typeof TheSacredJourneyRoute
  '/transmissions': typeof TransmissionsRoute
  '/true-timeline': typeof TrueTimelineRoute
  '/visit': typeof VisitRoute
  '/welcome': typeof WelcomeRoute
  '/wisdom': typeof WisdomRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/product/$handle': typeof ProductHandleRoute
  '/profile/$id': typeof ProfileIdRoute
  '/sovereign/terms': typeof SovereignTermsRoute
  '/sovereign/vip-waitlist': typeof SovereignVipWaitlistRoute
  '/sovereign/welcome': typeof SovereignWelcomeRoute
  '/wisdom_/matrix-origins': typeof WisdomMatrixOriginsRoute
  '/wisdom_/origins': typeof WisdomOriginsRoute
  '/wisdom_/plant-medicines': typeof WisdomPlantMedicinesRoute
  '/wisdom_/sacred-plants': typeof WisdomSacredPlantsRoute
  '/wisdom_/suppressed-sacred-texts': typeof WisdomSuppressedSacredTextsRoute
  '/wisdom_/the-true-story-of-jeshua': typeof WisdomTheTrueStoryOfJeshuaRoute
  '/sovereign/': typeof SovereignIndexRoute
  '/sovereign/portal/dashboard': typeof SovereignPortalDashboardRoute
  '/sovereign/portal/morning-ritual': typeof SovereignPortalMorningRitualRoute
  '/sovereign/portal/onboarding': typeof SovereignPortalOnboardingRoute
  '/sovereign/portal/': typeof SovereignPortalIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-codes'
    | '/astrology'
    | '/aura-reader'
    | '/awakening-assessment'
    | '/begin-here'
    | '/birth-chart'
    | '/blood-type'
    | '/book-session'
    | '/challenge'
    | '/consciousness-map'
    | '/contact'
    | '/contact-william'
    | '/dashboard'
    | '/discovery'
    | '/events'
    | '/gene-keys'
    | '/guide'
    | '/health'
    | '/hidden-truth'
    | '/higher-vibes'
    | '/horoscope'
    | '/kim-alfano'
    | '/meditations'
    | '/meet-william'
    | '/my-readings'
    | '/nature-booking'
    | '/numerology'
    | '/pillars'
    | '/practitioners'
    | '/readings'
    | '/reality-map'
    | '/services'
    | '/shop'
    | '/sign-in'
    | '/soul-profile'
    | '/soul-quiz'
    | '/sovereign'
    | '/store'
    | '/teachings'
    | '/the-sacred-journey'
    | '/transmissions'
    | '/true-timeline'
    | '/visit'
    | '/welcome'
    | '/wisdom'
    | '/checkout/return'
    | '/product/$handle'
    | '/profile/$id'
    | '/sovereign/terms'
    | '/sovereign/vip-waitlist'
    | '/sovereign/welcome'
    | '/wisdom/matrix-origins'
    | '/wisdom/origins'
    | '/wisdom/plant-medicines'
    | '/wisdom/sacred-plants'
    | '/wisdom/suppressed-sacred-texts'
    | '/wisdom/the-true-story-of-jeshua'
    | '/sovereign/'
    | '/sovereign/portal/dashboard'
    | '/sovereign/portal/morning-ritual'
    | '/sovereign/portal/onboarding'
    | '/sovereign/portal/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-codes'
    | '/astrology'
    | '/aura-reader'
    | '/awakening-assessment'
    | '/begin-here'
    | '/birth-chart'
    | '/blood-type'
    | '/book-session'
    | '/challenge'
    | '/consciousness-map'
    | '/contact'
    | '/contact-william'
    | '/dashboard'
    | '/discovery'
    | '/events'
    | '/gene-keys'
    | '/guide'
    | '/health'
    | '/hidden-truth'
    | '/higher-vibes'
    | '/horoscope'
    | '/kim-alfano'
    | '/meditations'
    | '/meet-william'
    | '/my-readings'
    | '/nature-booking'
    | '/numerology'
    | '/pillars'
    | '/practitioners'
    | '/readings'
    | '/reality-map'
    | '/services'
    | '/shop'
    | '/sign-in'
    | '/soul-profile'
    | '/soul-quiz'
    | '/store'
    | '/teachings'
    | '/the-sacred-journey'
    | '/transmissions'
    | '/true-timeline'
    | '/visit'
    | '/welcome'
    | '/wisdom'
    | '/checkout/return'
    | '/product/$handle'
    | '/profile/$id'
    | '/sovereign/terms'
    | '/sovereign/vip-waitlist'
    | '/sovereign/welcome'
    | '/wisdom/matrix-origins'
    | '/wisdom/origins'
    | '/wisdom/plant-medicines'
    | '/wisdom/sacred-plants'
    | '/wisdom/suppressed-sacred-texts'
    | '/wisdom/the-true-story-of-jeshua'
    | '/sovereign'
    | '/sovereign/portal/dashboard'
    | '/sovereign/portal/morning-ritual'
    | '/sovereign/portal/onboarding'
    | '/sovereign/portal'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-codes'
    | '/astrology'
    | '/aura-reader'
    | '/awakening-assessment'
    | '/begin-here'
    | '/birth-chart'
    | '/blood-type'
    | '/book-session'
    | '/challenge'
    | '/consciousness-map'
    | '/contact'
    | '/contact-william'
    | '/dashboard'
    | '/discovery'
    | '/events'
    | '/gene-keys'
    | '/guide'
    | '/health'
    | '/hidden-truth'
    | '/higher-vibes'
    | '/horoscope'
    | '/kim-alfano'
    | '/meditations'
    | '/meet-william'
    | '/my-readings'
    | '/nature-booking'
    | '/numerology'
    | '/pillars'
    | '/practitioners'
    | '/readings'
    | '/reality-map'
    | '/services'
    | '/shop'
    | '/sign-in'
    | '/soul-profile'
    | '/soul-quiz'
    | '/sovereign'
    | '/store'
    | '/teachings'
    | '/the-sacred-journey'
    | '/transmissions'
    | '/true-timeline'
    | '/visit'
    | '/welcome'
    | '/wisdom'
    | '/checkout/return'
    | '/product/$handle'
    | '/profile/$id'
    | '/sovereign/terms'
    | '/sovereign/vip-waitlist'
    | '/sovereign/welcome'
    | '/wisdom_/matrix-origins'
    | '/wisdom_/origins'
    | '/wisdom_/plant-medicines'
    | '/wisdom_/sacred-plants'
    | '/wisdom_/suppressed-sacred-texts'
    | '/wisdom_/the-true-story-of-jeshua'
    | '/sovereign/'
    | '/sovereign/portal/dashboard'
    | '/sovereign/portal/morning-ritual'
    | '/sovereign/portal/onboarding'
    | '/sovereign/portal/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminCodesRoute: typeof AdminCodesRoute
  AstrologyRoute: typeof AstrologyRoute
  AuraReaderRoute: typeof AuraReaderRoute
  AwakeningAssessmentRoute: typeof AwakeningAssessmentRoute
  BeginHereRoute: typeof BeginHereRoute
  BirthChartRoute: typeof BirthChartRoute
  BloodTypeRoute: typeof BloodTypeRoute
  BookSessionRoute: typeof BookSessionRoute
  ChallengeRoute: typeof ChallengeRoute
  ConsciousnessMapRoute: typeof ConsciousnessMapRoute
  ContactRoute: typeof ContactRoute
  ContactWilliamRoute: typeof ContactWilliamRoute
  DashboardRoute: typeof DashboardRoute
  DiscoveryRoute: typeof DiscoveryRoute
  EventsRoute: typeof EventsRoute
  GeneKeysRoute: typeof GeneKeysRoute
  GuideRoute: typeof GuideRoute
  HealthRoute: typeof HealthRoute
  HiddenTruthRoute: typeof HiddenTruthRoute
  HigherVibesRoute: typeof HigherVibesRoute
  HoroscopeRoute: typeof HoroscopeRoute
  KimAlfanoRoute: typeof KimAlfanoRoute
  MeditationsRoute: typeof MeditationsRoute
  MeetWilliamRoute: typeof MeetWilliamRoute
  MyReadingsRoute: typeof MyReadingsRoute
  NatureBookingRoute: typeof NatureBookingRoute
  NumerologyRoute: typeof NumerologyRoute
  PillarsRoute: typeof PillarsRoute
  PractitionersRoute: typeof PractitionersRoute
  ReadingsRoute: typeof ReadingsRoute
  RealityMapRoute: typeof RealityMapRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  SignInRoute: typeof SignInRoute
  SoulProfileRoute: typeof SoulProfileRoute
  SoulQuizRoute: typeof SoulQuizRoute
  SovereignRoute: typeof SovereignRouteWithChildren
  StoreRoute: typeof StoreRoute
  TeachingsRoute: typeof TeachingsRoute
  TheSacredJourneyRoute: typeof TheSacredJourneyRoute
  TransmissionsRoute: typeof TransmissionsRoute
  TrueTimelineRoute: typeof TrueTimelineRoute
  VisitRoute: typeof VisitRoute
  WelcomeRoute: typeof WelcomeRoute
  WisdomRoute: typeof WisdomRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ProfileIdRoute: typeof ProfileIdRoute
  WisdomMatrixOriginsRoute: typeof WisdomMatrixOriginsRoute
  WisdomOriginsRoute: typeof WisdomOriginsRoute
  WisdomPlantMedicinesRoute: typeof WisdomPlantMedicinesRoute
  WisdomSacredPlantsRoute: typeof WisdomSacredPlantsRoute
  WisdomSuppressedSacredTextsRoute: typeof WisdomSuppressedSacredTextsRoute
  WisdomTheTrueStoryOfJeshuaRoute: typeof WisdomTheTrueStoryOfJeshuaRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wisdom': {
      id: '/wisdom'
      path: '/wisdom'
      fullPath: '/wisdom'
      preLoaderRoute: typeof WisdomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/true-timeline': {
      id: '/true-timeline'
      path: '/true-timeline'
      fullPath: '/true-timeline'
      preLoaderRoute: typeof TrueTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transmissions': {
      id: '/transmissions'
      path: '/transmissions'
      fullPath: '/transmissions'
      preLoaderRoute: typeof TransmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-sacred-journey': {
      id: '/the-sacred-journey'
      path: '/the-sacred-journey'
      fullPath: '/the-sacred-journey'
      preLoaderRoute: typeof TheSacredJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachings': {
      id: '/teachings'
      path: '/teachings'
      fullPath: '/teachings'
      preLoaderRoute: typeof TeachingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sovereign': {
      id: '/sovereign'
      path: '/sovereign'
      fullPath: '/sovereign'
      preLoaderRoute: typeof SovereignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soul-quiz': {
      id: '/soul-quiz'
      path: '/soul-quiz'
      fullPath: '/soul-quiz'
      preLoaderRoute: typeof SoulQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soul-profile': {
      id: '/soul-profile'
      path: '/soul-profile'
      fullPath: '/soul-profile'
      preLoaderRoute: typeof SoulProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reality-map': {
      id: '/reality-map'
      path: '/reality-map'
      fullPath: '/reality-map'
      preLoaderRoute: typeof RealityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readings': {
      id: '/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof ReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioners': {
      id: '/practitioners'
      path: '/practitioners'
      fullPath: '/practitioners'
      preLoaderRoute: typeof PractitionersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillars': {
      id: '/pillars'
      path: '/pillars'
      fullPath: '/pillars'
      preLoaderRoute: typeof PillarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numerology': {
      id: '/numerology'
      path: '/numerology'
      fullPath: '/numerology'
      preLoaderRoute: typeof NumerologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nature-booking': {
      id: '/nature-booking'
      path: '/nature-booking'
      fullPath: '/nature-booking'
      preLoaderRoute: typeof NatureBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-readings': {
      id: '/my-readings'
      path: '/my-readings'
      fullPath: '/my-readings'
      preLoaderRoute: typeof MyReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-william': {
      id: '/meet-william'
      path: '/meet-william'
      fullPath: '/meet-william'
      preLoaderRoute: typeof MeetWilliamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meditations': {
      id: '/meditations'
      path: '/meditations'
      fullPath: '/meditations'
      preLoaderRoute: typeof MeditationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kim-alfano': {
      id: '/kim-alfano'
      path: '/kim-alfano'
      fullPath: '/kim-alfano'
      preLoaderRoute: typeof KimAlfanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscope': {
      id: '/horoscope'
      path: '/horoscope'
      fullPath: '/horoscope'
      preLoaderRoute: typeof HoroscopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/higher-vibes': {
      id: '/higher-vibes'
      path: '/higher-vibes'
      fullPath: '/higher-vibes'
      preLoaderRoute: typeof HigherVibesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden-truth': {
      id: '/hidden-truth'
      path: '/hidden-truth'
      fullPath: '/hidden-truth'
      preLoaderRoute: typeof HiddenTruthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gene-keys': {
      id: '/gene-keys'
      path: '/gene-keys'
      fullPath: '/gene-keys'
      preLoaderRoute: typeof GeneKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-william': {
      id: '/contact-william'
      path: '/contact-william'
      fullPath: '/contact-william'
      preLoaderRoute: typeof ContactWilliamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consciousness-map': {
      id: '/consciousness-map'
      path: '/consciousness-map'
      fullPath: '/consciousness-map'
      preLoaderRoute: typeof ConsciousnessMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-session': {
      id: '/book-session'
      path: '/book-session'
      fullPath: '/book-session'
      preLoaderRoute: typeof BookSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blood-type': {
      id: '/blood-type'
      path: '/blood-type'
      fullPath: '/blood-type'
      preLoaderRoute: typeof BloodTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birth-chart': {
      id: '/birth-chart'
      path: '/birth-chart'
      fullPath: '/birth-chart'
      preLoaderRoute: typeof BirthChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begin-here': {
      id: '/begin-here'
      path: '/begin-here'
      fullPath: '/begin-here'
      preLoaderRoute: typeof BeginHereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awakening-assessment': {
      id: '/awakening-assessment'
      path: '/awakening-assessment'
      fullPath: '/awakening-assessment'
      preLoaderRoute: typeof AwakeningAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura-reader': {
      id: '/aura-reader'
      path: '/aura-reader'
      fullPath: '/aura-reader'
      preLoaderRoute: typeof AuraReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology': {
      id: '/astrology'
      path: '/astrology'
      fullPath: '/astrology'
      preLoaderRoute: typeof AstrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-codes': {
      id: '/admin-codes'
      path: '/admin-codes'
      fullPath: '/admin-codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sovereign/': {
      id: '/sovereign/'
      path: '/'
      fullPath: '/sovereign/'
      preLoaderRoute: typeof SovereignIndexRouteImport
      parentRoute: typeof SovereignRoute
    }
    '/wisdom_/the-true-story-of-jeshua': {
      id: '/wisdom_/the-true-story-of-jeshua'
      path: '/wisdom/the-true-story-of-jeshua'
      fullPath: '/wisdom/the-true-story-of-jeshua'
      preLoaderRoute: typeof WisdomTheTrueStoryOfJeshuaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom_/suppressed-sacred-texts': {
      id: '/wisdom_/suppressed-sacred-texts'
      path: '/wisdom/suppressed-sacred-texts'
      fullPath: '/wisdom/suppressed-sacred-texts'
      preLoaderRoute: typeof WisdomSuppressedSacredTextsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom_/sacred-plants': {
      id: '/wisdom_/sacred-plants'
      path: '/wisdom/sacred-plants'
      fullPath: '/wisdom/sacred-plants'
      preLoaderRoute: typeof WisdomSacredPlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom_/plant-medicines': {
      id: '/wisdom_/plant-medicines'
      path: '/wisdom/plant-medicines'
      fullPath: '/wisdom/plant-medicines'
      preLoaderRoute: typeof WisdomPlantMedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom_/origins': {
      id: '/wisdom_/origins'
      path: '/wisdom/origins'
      fullPath: '/wisdom/origins'
      preLoaderRoute: typeof WisdomOriginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom_/matrix-origins': {
      id: '/wisdom_/matrix-origins'
      path: '/wisdom/matrix-origins'
      fullPath: '/wisdom/matrix-origins'
      preLoaderRoute: typeof WisdomMatrixOriginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sovereign/welcome': {
      id: '/sovereign/welcome'
      path: '/welcome'
      fullPath: '/sovereign/welcome'
      preLoaderRoute: typeof SovereignWelcomeRouteImport
      parentRoute: typeof SovereignRoute
    }
    '/sovereign/vip-waitlist': {
      id: '/sovereign/vip-waitlist'
      path: '/vip-waitlist'
      fullPath: '/sovereign/vip-waitlist'
      preLoaderRoute: typeof SovereignVipWaitlistRouteImport
      parentRoute: typeof SovereignRoute
    }
    '/sovereign/terms': {
      id: '/sovereign/terms'
      path: '/terms'
      fullPath: '/sovereign/terms'
      preLoaderRoute: typeof SovereignTermsRouteImport
      parentRoute: typeof SovereignRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sovereign/portal/': {
      id: '/sovereign/portal/'
      path: '/portal'
      fullPath: '/sovereign/portal/'
      preLoaderRoute: typeof SovereignPortalIndexRouteImport
      parentRoute: typeof SovereignRoute
    }
    '/sovereign/portal/onboarding': {
      id: '/sovereign/portal/onboarding'
      path: '/portal/onboarding'
      fullPath: '/sovereign/portal/onboarding'
      preLoaderRoute: typeof SovereignPortalOnboardingRouteImport
      parentRoute: typeof SovereignRoute
    }
    '/sovereign/portal/morning-ritual': {
      id: '/sovereign/portal/morning-ritual'
      path: '/portal/morning-ritual'
      fullPath: '/sovereign/portal/morning-ritual'
      preLoaderRoute: typeof SovereignPortalMorningRitualRouteImport
      parentRoute: typeof SovereignRoute
    }
    '/sovereign/portal/dashboard': {
      id: '/sovereign/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/sovereign/portal/dashboard'
      preLoaderRoute: typeof SovereignPortalDashboardRouteImport
      parentRoute: typeof SovereignRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SovereignRouteChildren {
  SovereignTermsRoute: typeof SovereignTermsRoute
  SovereignVipWaitlistRoute: typeof SovereignVipWaitlistRoute
  SovereignWelcomeRoute: typeof SovereignWelcomeRoute
  SovereignIndexRoute: typeof SovereignIndexRoute
  SovereignPortalDashboardRoute: typeof SovereignPortalDashboardRoute
  SovereignPortalMorningRitualRoute: typeof SovereignPortalMorningRitualRoute
  SovereignPortalOnboardingRoute: typeof SovereignPortalOnboardingRoute
  SovereignPortalIndexRoute: typeof SovereignPortalIndexRoute
}

const SovereignRouteChildren: SovereignRouteChildren = {
  SovereignTermsRoute: SovereignTermsRoute,
  SovereignVipWaitlistRoute: SovereignVipWaitlistRoute,
  SovereignWelcomeRoute: SovereignWelcomeRoute,
  SovereignIndexRoute: SovereignIndexRoute,
  SovereignPortalDashboardRoute: SovereignPortalDashboardRoute,
  SovereignPortalMorningRitualRoute: SovereignPortalMorningRitualRoute,
  SovereignPortalOnboardingRoute: SovereignPortalOnboardingRoute,
  SovereignPortalIndexRoute: SovereignPortalIndexRoute,
}

const SovereignRouteWithChildren = SovereignRoute._addFileChildren(
  SovereignRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminCodesRoute: AdminCodesRoute,
  AstrologyRoute: AstrologyRoute,
  AuraReaderRoute: AuraReaderRoute,
  AwakeningAssessmentRoute: AwakeningAssessmentRoute,
  BeginHereRoute: BeginHereRoute,
  BirthChartRoute: BirthChartRoute,
  BloodTypeRoute: BloodTypeRoute,
  BookSessionRoute: BookSessionRoute,
  ChallengeRoute: ChallengeRoute,
  ConsciousnessMapRoute: ConsciousnessMapRoute,
  ContactRoute: ContactRoute,
  ContactWilliamRoute: ContactWilliamRoute,
  DashboardRoute: DashboardRoute,
  DiscoveryRoute: DiscoveryRoute,
  EventsRoute: EventsRoute,
  GeneKeysRoute: GeneKeysRoute,
  GuideRoute: GuideRoute,
  HealthRoute: HealthRoute,
  HiddenTruthRoute: HiddenTruthRoute,
  HigherVibesRoute: HigherVibesRoute,
  HoroscopeRoute: HoroscopeRoute,
  KimAlfanoRoute: KimAlfanoRoute,
  MeditationsRoute: MeditationsRoute,
  MeetWilliamRoute: MeetWilliamRoute,
  MyReadingsRoute: MyReadingsRoute,
  NatureBookingRoute: NatureBookingRoute,
  NumerologyRoute: NumerologyRoute,
  PillarsRoute: PillarsRoute,
  PractitionersRoute: PractitionersRoute,
  ReadingsRoute: ReadingsRoute,
  RealityMapRoute: RealityMapRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  SignInRoute: SignInRoute,
  SoulProfileRoute: SoulProfileRoute,
  SoulQuizRoute: SoulQuizRoute,
  SovereignRoute: SovereignRouteWithChildren,
  StoreRoute: StoreRoute,
  TeachingsRoute: TeachingsRoute,
  TheSacredJourneyRoute: TheSacredJourneyRoute,
  TransmissionsRoute: TransmissionsRoute,
  TrueTimelineRoute: TrueTimelineRoute,
  VisitRoute: VisitRoute,
  WelcomeRoute: WelcomeRoute,
  WisdomRoute: WisdomRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ProductHandleRoute: ProductHandleRoute,
  ProfileIdRoute: ProfileIdRoute,
  WisdomMatrixOriginsRoute: WisdomMatrixOriginsRoute,
  WisdomOriginsRoute: WisdomOriginsRoute,
  WisdomPlantMedicinesRoute: WisdomPlantMedicinesRoute,
  WisdomSacredPlantsRoute: WisdomSacredPlantsRoute,
  WisdomSuppressedSacredTextsRoute: WisdomSuppressedSacredTextsRoute,
  WisdomTheTrueStoryOfJeshuaRoute: WisdomTheTrueStoryOfJeshuaRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
