/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as TrueTimelineRouteImport } from './routes/true-timeline'
import { Route as TeachingsRouteImport } from './routes/teachings'
import { Route as SoulProfileRouteImport } from './routes/soul-profile'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RealityMapRouteImport } from './routes/reality-map'
import { Route as PractitionersRouteImport } from './routes/practitioners'
import { Route as NatureBookingRouteImport } from './routes/nature-booking'
import { Route as MyReadingsRouteImport } from './routes/my-readings'
import { Route as MeditationsRouteImport } from './routes/meditations'
import { Route as IrisReaderRouteImport } from './routes/iris-reader'
import { Route as HiddenTruthRouteImport } from './routes/hidden-truth'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as FingerprintReaderRouteImport } from './routes/fingerprint-reader'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactWilliamRouteImport } from './routes/contact-william'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsciousnessMapRouteImport } from './routes/consciousness-map'
import { Route as BeginHereRouteImport } from './routes/begin-here'
import { Route as AwakeningAssessmentRouteImport } from './routes/awakening-assessment'
import { Route as AuraReaderRouteImport } from './routes/aura-reader'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const TrueTimelineRoute = TrueTimelineRouteImport.update({
  id: '/true-timeline',
  path: '/true-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingsRoute = TeachingsRouteImport.update({
  id: '/teachings',
  path: '/teachings',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulProfileRoute = SoulProfileRouteImport.update({
  id: '/soul-profile',
  path: '/soul-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RealityMapRoute = RealityMapRouteImport.update({
  id: '/reality-map',
  path: '/reality-map',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionersRoute = PractitionersRouteImport.update({
  id: '/practitioners',
  path: '/practitioners',
  getParentRoute: () => rootRouteImport,
} as any)
const NatureBookingRoute = NatureBookingRouteImport.update({
  id: '/nature-booking',
  path: '/nature-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReadingsRoute = MyReadingsRouteImport.update({
  id: '/my-readings',
  path: '/my-readings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeditationsRoute = MeditationsRouteImport.update({
  id: '/meditations',
  path: '/meditations',
  getParentRoute: () => rootRouteImport,
} as any)
const IrisReaderRoute = IrisReaderRouteImport.update({
  id: '/iris-reader',
  path: '/iris-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const HiddenTruthRoute = HiddenTruthRouteImport.update({
  id: '/hidden-truth',
  path: '/hidden-truth',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FingerprintReaderRoute = FingerprintReaderRouteImport.update({
  id: '/fingerprint-reader',
  path: '/fingerprint-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactWilliamRoute = ContactWilliamRouteImport.update({
  id: '/contact-william',
  path: '/contact-william',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsciousnessMapRoute = ConsciousnessMapRouteImport.update({
  id: '/consciousness-map',
  path: '/consciousness-map',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginHereRoute = BeginHereRouteImport.update({
  id: '/begin-here',
  path: '/begin-here',
  getParentRoute: () => rootRouteImport,
} as any)
const AwakeningAssessmentRoute = AwakeningAssessmentRouteImport.update({
  id: '/awakening-assessment',
  path: '/awakening-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraReaderRoute = AuraReaderRouteImport.update({
  id: '/aura-reader',
  path: '/aura-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/aura-reader': typeof AuraReaderRoute
  '/awakening-assessment': typeof AwakeningAssessmentRoute
  '/begin-here': typeof BeginHereRoute
  '/consciousness-map': typeof ConsciousnessMapRoute
  '/contact': typeof ContactRoute
  '/contact-william': typeof ContactWilliamRoute
  '/dashboard': typeof DashboardRoute
  '/discovery': typeof DiscoveryRoute
  '/events': typeof EventsRoute
  '/fingerprint-reader': typeof FingerprintReaderRoute
  '/guide': typeof GuideRoute
  '/health': typeof HealthRoute
  '/hidden-truth': typeof HiddenTruthRoute
  '/iris-reader': typeof IrisReaderRoute
  '/meditations': typeof MeditationsRoute
  '/my-readings': typeof MyReadingsRoute
  '/nature-booking': typeof NatureBookingRoute
  '/practitioners': typeof PractitionersRoute
  '/reality-map': typeof RealityMapRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/soul-profile': typeof SoulProfileRoute
  '/teachings': typeof TeachingsRoute
  '/true-timeline': typeof TrueTimelineRoute
  '/visit': typeof VisitRoute
  '/welcome': typeof WelcomeRoute
  '/product/$handle': typeof ProductHandleRoute
  '/profile/$id': typeof ProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/aura-reader': typeof AuraReaderRoute
  '/awakening-assessment': typeof AwakeningAssessmentRoute
  '/begin-here': typeof BeginHereRoute
  '/consciousness-map': typeof ConsciousnessMapRoute
  '/contact': typeof ContactRoute
  '/contact-william': typeof ContactWilliamRoute
  '/dashboard': typeof DashboardRoute
  '/discovery': typeof DiscoveryRoute
  '/events': typeof EventsRoute
  '/fingerprint-reader': typeof FingerprintReaderRoute
  '/guide': typeof GuideRoute
  '/health': typeof HealthRoute
  '/hidden-truth': typeof HiddenTruthRoute
  '/iris-reader': typeof IrisReaderRoute
  '/meditations': typeof MeditationsRoute
  '/my-readings': typeof MyReadingsRoute
  '/nature-booking': typeof NatureBookingRoute
  '/practitioners': typeof PractitionersRoute
  '/reality-map': typeof RealityMapRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/soul-profile': typeof SoulProfileRoute
  '/teachings': typeof TeachingsRoute
  '/true-timeline': typeof TrueTimelineRoute
  '/visit': typeof VisitRoute
  '/welcome': typeof WelcomeRoute
  '/product/$handle': typeof ProductHandleRoute
  '/profile/$id': typeof ProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/aura-reader': typeof AuraReaderRoute
  '/awakening-assessment': typeof AwakeningAssessmentRoute
  '/begin-here': typeof BeginHereRoute
  '/consciousness-map': typeof ConsciousnessMapRoute
  '/contact': typeof ContactRoute
  '/contact-william': typeof ContactWilliamRoute
  '/dashboard': typeof DashboardRoute
  '/discovery': typeof DiscoveryRoute
  '/events': typeof EventsRoute
  '/fingerprint-reader': typeof FingerprintReaderRoute
  '/guide': typeof GuideRoute
  '/health': typeof HealthRoute
  '/hidden-truth': typeof HiddenTruthRoute
  '/iris-reader': typeof IrisReaderRoute
  '/meditations': typeof MeditationsRoute
  '/my-readings': typeof MyReadingsRoute
  '/nature-booking': typeof NatureBookingRoute
  '/practitioners': typeof PractitionersRoute
  '/reality-map': typeof RealityMapRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/soul-profile': typeof SoulProfileRoute
  '/teachings': typeof TeachingsRoute
  '/true-timeline': typeof TrueTimelineRoute
  '/visit': typeof VisitRoute
  '/welcome': typeof WelcomeRoute
  '/product/$handle': typeof ProductHandleRoute
  '/profile/$id': typeof ProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/aura-reader'
    | '/awakening-assessment'
    | '/begin-here'
    | '/consciousness-map'
    | '/contact'
    | '/contact-william'
    | '/dashboard'
    | '/discovery'
    | '/events'
    | '/fingerprint-reader'
    | '/guide'
    | '/health'
    | '/hidden-truth'
    | '/iris-reader'
    | '/meditations'
    | '/my-readings'
    | '/nature-booking'
    | '/practitioners'
    | '/reality-map'
    | '/services'
    | '/shop'
    | '/sign-in'
    | '/soul-profile'
    | '/teachings'
    | '/true-timeline'
    | '/visit'
    | '/welcome'
    | '/product/$handle'
    | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/aura-reader'
    | '/awakening-assessment'
    | '/begin-here'
    | '/consciousness-map'
    | '/contact'
    | '/contact-william'
    | '/dashboard'
    | '/discovery'
    | '/events'
    | '/fingerprint-reader'
    | '/guide'
    | '/health'
    | '/hidden-truth'
    | '/iris-reader'
    | '/meditations'
    | '/my-readings'
    | '/nature-booking'
    | '/practitioners'
    | '/reality-map'
    | '/services'
    | '/shop'
    | '/sign-in'
    | '/soul-profile'
    | '/teachings'
    | '/true-timeline'
    | '/visit'
    | '/welcome'
    | '/product/$handle'
    | '/profile/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/aura-reader'
    | '/awakening-assessment'
    | '/begin-here'
    | '/consciousness-map'
    | '/contact'
    | '/contact-william'
    | '/dashboard'
    | '/discovery'
    | '/events'
    | '/fingerprint-reader'
    | '/guide'
    | '/health'
    | '/hidden-truth'
    | '/iris-reader'
    | '/meditations'
    | '/my-readings'
    | '/nature-booking'
    | '/practitioners'
    | '/reality-map'
    | '/services'
    | '/shop'
    | '/sign-in'
    | '/soul-profile'
    | '/teachings'
    | '/true-timeline'
    | '/visit'
    | '/welcome'
    | '/product/$handle'
    | '/profile/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuraReaderRoute: typeof AuraReaderRoute
  AwakeningAssessmentRoute: typeof AwakeningAssessmentRoute
  BeginHereRoute: typeof BeginHereRoute
  ConsciousnessMapRoute: typeof ConsciousnessMapRoute
  ContactRoute: typeof ContactRoute
  ContactWilliamRoute: typeof ContactWilliamRoute
  DashboardRoute: typeof DashboardRoute
  DiscoveryRoute: typeof DiscoveryRoute
  EventsRoute: typeof EventsRoute
  FingerprintReaderRoute: typeof FingerprintReaderRoute
  GuideRoute: typeof GuideRoute
  HealthRoute: typeof HealthRoute
  HiddenTruthRoute: typeof HiddenTruthRoute
  IrisReaderRoute: typeof IrisReaderRoute
  MeditationsRoute: typeof MeditationsRoute
  MyReadingsRoute: typeof MyReadingsRoute
  NatureBookingRoute: typeof NatureBookingRoute
  PractitionersRoute: typeof PractitionersRoute
  RealityMapRoute: typeof RealityMapRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  SignInRoute: typeof SignInRoute
  SoulProfileRoute: typeof SoulProfileRoute
  TeachingsRoute: typeof TeachingsRoute
  TrueTimelineRoute: typeof TrueTimelineRoute
  VisitRoute: typeof VisitRoute
  WelcomeRoute: typeof WelcomeRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ProfileIdRoute: typeof ProfileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/true-timeline': {
      id: '/true-timeline'
      path: '/true-timeline'
      fullPath: '/true-timeline'
      preLoaderRoute: typeof TrueTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachings': {
      id: '/teachings'
      path: '/teachings'
      fullPath: '/teachings'
      preLoaderRoute: typeof TeachingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soul-profile': {
      id: '/soul-profile'
      path: '/soul-profile'
      fullPath: '/soul-profile'
      preLoaderRoute: typeof SoulProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reality-map': {
      id: '/reality-map'
      path: '/reality-map'
      fullPath: '/reality-map'
      preLoaderRoute: typeof RealityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioners': {
      id: '/practitioners'
      path: '/practitioners'
      fullPath: '/practitioners'
      preLoaderRoute: typeof PractitionersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nature-booking': {
      id: '/nature-booking'
      path: '/nature-booking'
      fullPath: '/nature-booking'
      preLoaderRoute: typeof NatureBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-readings': {
      id: '/my-readings'
      path: '/my-readings'
      fullPath: '/my-readings'
      preLoaderRoute: typeof MyReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meditations': {
      id: '/meditations'
      path: '/meditations'
      fullPath: '/meditations'
      preLoaderRoute: typeof MeditationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iris-reader': {
      id: '/iris-reader'
      path: '/iris-reader'
      fullPath: '/iris-reader'
      preLoaderRoute: typeof IrisReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden-truth': {
      id: '/hidden-truth'
      path: '/hidden-truth'
      fullPath: '/hidden-truth'
      preLoaderRoute: typeof HiddenTruthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fingerprint-reader': {
      id: '/fingerprint-reader'
      path: '/fingerprint-reader'
      fullPath: '/fingerprint-reader'
      preLoaderRoute: typeof FingerprintReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-william': {
      id: '/contact-william'
      path: '/contact-william'
      fullPath: '/contact-william'
      preLoaderRoute: typeof ContactWilliamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consciousness-map': {
      id: '/consciousness-map'
      path: '/consciousness-map'
      fullPath: '/consciousness-map'
      preLoaderRoute: typeof ConsciousnessMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begin-here': {
      id: '/begin-here'
      path: '/begin-here'
      fullPath: '/begin-here'
      preLoaderRoute: typeof BeginHereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awakening-assessment': {
      id: '/awakening-assessment'
      path: '/awakening-assessment'
      fullPath: '/awakening-assessment'
      preLoaderRoute: typeof AwakeningAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura-reader': {
      id: '/aura-reader'
      path: '/aura-reader'
      fullPath: '/aura-reader'
      preLoaderRoute: typeof AuraReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuraReaderRoute: AuraReaderRoute,
  AwakeningAssessmentRoute: AwakeningAssessmentRoute,
  BeginHereRoute: BeginHereRoute,
  ConsciousnessMapRoute: ConsciousnessMapRoute,
  ContactRoute: ContactRoute,
  ContactWilliamRoute: ContactWilliamRoute,
  DashboardRoute: DashboardRoute,
  DiscoveryRoute: DiscoveryRoute,
  EventsRoute: EventsRoute,
  FingerprintReaderRoute: FingerprintReaderRoute,
  GuideRoute: GuideRoute,
  HealthRoute: HealthRoute,
  HiddenTruthRoute: HiddenTruthRoute,
  IrisReaderRoute: IrisReaderRoute,
  MeditationsRoute: MeditationsRoute,
  MyReadingsRoute: MyReadingsRoute,
  NatureBookingRoute: NatureBookingRoute,
  PractitionersRoute: PractitionersRoute,
  RealityMapRoute: RealityMapRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  SignInRoute: SignInRoute,
  SoulProfileRoute: SoulProfileRoute,
  TeachingsRoute: TeachingsRoute,
  TrueTimelineRoute: TrueTimelineRoute,
  VisitRoute: VisitRoute,
  WelcomeRoute: WelcomeRoute,
  ProductHandleRoute: ProductHandleRoute,
  ProfileIdRoute: ProfileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
